//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidyano.Service.EntityFrameworkCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vidyano.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET QUOTED_IDENTIFIER OFF;
        ///GO
        ///IF SCHEMA_ID(N&apos;Vidyano&apos;) IS NULL EXECUTE(N&apos;CREATE SCHEMA [Vidyano]&apos;);
        ///GO
        ///
        ///-- Creating table &apos;Users&apos;
        ///CREATE TABLE [Vidyano].[Users] (
        ///    [Id] uniqueidentifier  NOT NULL,
        ///    [Name] nvarchar(255)  NOT NULL,
        ///    [FriendlyName] nvarchar(max)  NULL,
        ///    [PasswordHash] varchar(max)  NOT NULL,
        ///    [Language] varchar(10)  NOT NULL,
        ///    [CultureInfo] varchar(10) NOT NULL,
        ///    [Version] varchar(100)  NOT NULL,
        ///    [CreationDate] datetimeoffset(3)  NOT NULL,
        ///    [LastLogin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RepositorySql {
            get {
                return ResourceManager.GetString("RepositorySql", resourceCulture);
            }
        }
    }
}
